# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Bitcoin_cost.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QGroupBox, QLabel,
    QLineEdit, QMainWindow, QMenuBar, QSizePolicy,
    QStatusBar, QTabWidget, QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(942, 685)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.comboBox = QComboBox(self.centralwidget)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(730, 0, 69, 22))
        self.label_15M = QLabel(self.centralwidget)
        self.label_15M.setObjectName(u"label_15M")
        self.label_15M.setGeometry(QRect(70, 40, 70, 20))
        self.label_15M.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_1H = QLabel(self.centralwidget)
        self.label_1H.setObjectName(u"label_1H")
        self.label_1H.setGeometry(QRect(260, 40, 70, 20))
        self.label_1H.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_4h = QLabel(self.centralwidget)
        self.label_4h.setObjectName(u"label_4h")
        self.label_4h.setGeometry(QRect(460, 40, 70, 20))
        self.label_4h.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_15M = QLineEdit(self.centralwidget)
        self.lineEdit_15M.setObjectName(u"lineEdit_15M")
        self.lineEdit_15M.setGeometry(QRect(140, 40, 100, 20))
        self.lineEdit_1H = QLineEdit(self.centralwidget)
        self.lineEdit_1H.setObjectName(u"lineEdit_1H")
        self.lineEdit_1H.setGeometry(QRect(340, 40, 100, 20))
        self.lineEdit_4H = QLineEdit(self.centralwidget)
        self.lineEdit_4H.setObjectName(u"lineEdit_4H")
        self.lineEdit_4H.setGeometry(QRect(540, 40, 100, 20))
        self.label_TimeNow = QLabel(self.centralwidget)
        self.label_TimeNow.setObjectName(u"label_TimeNow")
        self.label_TimeNow.setGeometry(QRect(80, 60, 150, 20))
        self.tabWidget_Graph = QTabWidget(self.centralwidget)
        self.tabWidget_Graph.setObjectName(u"tabWidget_Graph")
        self.tabWidget_Graph.setGeometry(QRect(80, 240, 771, 391))
        self.tab_15M = QWidget()
        self.tab_15M.setObjectName(u"tab_15M")
        self.verticalLayoutWidget = QWidget(self.tab_15M)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(-1, -1, 771, 371))
        self.verticalLayout_Predict_15M = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_Predict_15M.setObjectName(u"verticalLayout_Predict_15M")
        self.verticalLayout_Predict_15M.setContentsMargins(0, 0, 0, 0)
        self.tabWidget_Graph.addTab(self.tab_15M, "")
        self.tab_1H = QWidget()
        self.tab_1H.setObjectName(u"tab_1H")
        self.verticalLayoutWidget_2 = QWidget(self.tab_1H)
        self.verticalLayoutWidget_2.setObjectName(u"verticalLayoutWidget_2")
        self.verticalLayoutWidget_2.setGeometry(QRect(-1, -1, 771, 371))
        self.verticalLayout_Predict_1H = QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_Predict_1H.setObjectName(u"verticalLayout_Predict_1H")
        self.verticalLayout_Predict_1H.setContentsMargins(0, 0, 0, 0)
        self.tabWidget_Graph.addTab(self.tab_1H, "")
        self.tab_4H = QWidget()
        self.tab_4H.setObjectName(u"tab_4H")
        self.verticalLayoutWidget_3 = QWidget(self.tab_4H)
        self.verticalLayoutWidget_3.setObjectName(u"verticalLayoutWidget_3")
        self.verticalLayoutWidget_3.setGeometry(QRect(-1, -1, 771, 371))
        self.verticalLayout_Predict_4H = QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_Predict_4H.setObjectName(u"verticalLayout_Predict_4H")
        self.verticalLayout_Predict_4H.setContentsMargins(0, 0, 0, 0)
        self.tabWidget_Graph.addTab(self.tab_4H, "")
        self.label_Current_Cost = QLabel(self.centralwidget)
        self.label_Current_Cost.setObjectName(u"label_Current_Cost")
        self.label_Current_Cost.setGeometry(QRect(60, 10, 80, 20))
        self.lineEdit_Current_cost = QLineEdit(self.centralwidget)
        self.lineEdit_Current_cost.setObjectName(u"lineEdit_Current_cost")
        self.lineEdit_Current_cost.setGeometry(QRect(140, 10, 100, 20))
        self.groupBox_Analysis = QGroupBox(self.centralwidget)
        self.groupBox_Analysis.setObjectName(u"groupBox_Analysis")
        self.groupBox_Analysis.setGeometry(QRect(20, 90, 911, 141))
        font = QFont()
        font.setPointSize(11)
        self.groupBox_Analysis.setFont(font)
        self.label_Analysis_15M = QLabel(self.groupBox_Analysis)
        self.label_Analysis_15M.setObjectName(u"label_Analysis_15M")
        self.label_Analysis_15M.setGeometry(QRect(20, 90, 150, 20))
        self.label_Result_15M = QLabel(self.groupBox_Analysis)
        self.label_Result_15M.setObjectName(u"label_Result_15M")
        self.label_Result_15M.setGeometry(QRect(180, 90, 121, 20))
        self.label_Analysis_1H = QLabel(self.groupBox_Analysis)
        self.label_Analysis_1H.setObjectName(u"label_Analysis_1H")
        self.label_Analysis_1H.setGeometry(QRect(320, 90, 150, 20))
        self.label_Result_1H = QLabel(self.groupBox_Analysis)
        self.label_Result_1H.setObjectName(u"label_Result_1H")
        self.label_Result_1H.setGeometry(QRect(480, 90, 121, 20))
        self.label_Analysis_4H = QLabel(self.groupBox_Analysis)
        self.label_Analysis_4H.setObjectName(u"label_Analysis_4H")
        self.label_Analysis_4H.setGeometry(QRect(615, 90, 150, 20))
        self.label_Result_4H = QLabel(self.groupBox_Analysis)
        self.label_Result_4H.setObjectName(u"label_Result_4H")
        self.label_Result_4H.setGeometry(QRect(765, 90, 121, 20))
        self.lineEdit_Acture_value = QLineEdit(self.groupBox_Analysis)
        self.lineEdit_Acture_value.setObjectName(u"lineEdit_Acture_value")
        self.lineEdit_Acture_value.setGeometry(QRect(100, 60, 100, 20))
        self.label_Acture_value = QLabel(self.groupBox_Analysis)
        self.label_Acture_value.setObjectName(u"label_Acture_value")
        self.label_Acture_value.setGeometry(QRect(100, 30, 150, 20))
        self.lineEdit_Acture_value_2 = QLineEdit(self.groupBox_Analysis)
        self.lineEdit_Acture_value_2.setObjectName(u"lineEdit_Acture_value_2")
        self.lineEdit_Acture_value_2.setGeometry(QRect(400, 60, 100, 20))
        self.label_Acture_value_2 = QLabel(self.groupBox_Analysis)
        self.label_Acture_value_2.setObjectName(u"label_Acture_value_2")
        self.label_Acture_value_2.setGeometry(QRect(400, 30, 150, 20))
        self.lineEdit_Acture_value_3 = QLineEdit(self.groupBox_Analysis)
        self.lineEdit_Acture_value_3.setObjectName(u"lineEdit_Acture_value_3")
        self.lineEdit_Acture_value_3.setGeometry(QRect(660, 60, 100, 20))
        self.label_Acture_value_3 = QLabel(self.groupBox_Analysis)
        self.label_Acture_value_3.setObjectName(u"label_Acture_value_3")
        self.label_Acture_value_3.setGeometry(QRect(660, 30, 150, 20))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 942, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.tabWidget_Graph.setCurrentIndex(2)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.comboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"BTC", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"ETH", None))

        self.label_15M.setText(QCoreApplication.translate("MainWindow", u"15M Later", None))
        self.label_1H.setText(QCoreApplication.translate("MainWindow", u"1H Later", None))
        self.label_4h.setText(QCoreApplication.translate("MainWindow", u"4H Later", None))
        self.label_TimeNow.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.tabWidget_Graph.setTabText(self.tabWidget_Graph.indexOf(self.tab_15M), QCoreApplication.translate("MainWindow", u"Predict 15M", None))
        self.tabWidget_Graph.setTabText(self.tabWidget_Graph.indexOf(self.tab_1H), QCoreApplication.translate("MainWindow", u"Predict 1H", None))
        self.tabWidget_Graph.setTabText(self.tabWidget_Graph.indexOf(self.tab_4H), QCoreApplication.translate("MainWindow", u"Predict 4H", None))
        self.label_Current_Cost.setText(QCoreApplication.translate("MainWindow", u"Current Cost", None))
        self.groupBox_Analysis.setTitle(QCoreApplication.translate("MainWindow", u"Analysis", None))
        self.label_Analysis_15M.setText(QCoreApplication.translate("MainWindow", u"15M: ", None))
        self.label_Result_15M.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.label_Analysis_1H.setText(QCoreApplication.translate("MainWindow", u"1 H: ", None))
        self.label_Result_1H.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.label_Analysis_4H.setText(QCoreApplication.translate("MainWindow", u"4 H: ", None))
        self.label_Result_4H.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.label_Acture_value.setText(QCoreApplication.translate("MainWindow", u"Cost at Predict time", None))
        self.label_Acture_value_2.setText(QCoreApplication.translate("MainWindow", u"Cost at Predict time", None))
        self.label_Acture_value_3.setText(QCoreApplication.translate("MainWindow", u"Cost at Predict time", None))
    # retranslateUi

